# Copyright 2017 Amazon Web Services, Inc. or its affiliates. All Rights Reserved.
# Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with the License. A copy of the License is located at
#    http://aws.amazon.com/apache2.0/
# or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

AWSTemplateFormatVersion: '2010-09-09'
Description: Backend for photo sharing reference architecture.
Transform: 'AWS::Serverless-2016-10-31'

Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 30
    Environment:
      Variables:
        LOG_LEVEL: "INFO"
        GRAPHQL_API_ENDPOINT: !Ref GraphQLEndPoint

Parameters:
  PhotoRepoS3Bucket:
    Description: s3 bucket for photo uploads
    Type: String
  GraphQLEndPoint:
    Description: graph QL endpoint
    Type: String
  GraphQLAPIId:
    Description: graph QL API ID
    Type: String
  Stage:
    Type: String
    Description: Environment stage or git branch

Resources:
  # ---------------------------------------------------------------------------------------------------------------------
  # This group of Lambda functions below make up the Step Functions state machine to execute the image processing workflow
  # ---------------------------------------------------------------------------------------------------------------------
  ImageMagick:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:145266761615:applications/image-magick-lambda-layer
        SemanticVersion: 1.0.0

  ExtractImageMetadataFunction:
    Properties:
      CodeUri:        ../lambda-functions/extract-image-metadata
      Description: "Extract image metadata such as format, size, geolocation, etc."
      Handler: index.handler
      MemorySize: 1024
      Timeout: 200
      Policies:
        - S3ReadPolicy:
            BucketName:
              !Ref PhotoRepoS3Bucket
      Layers:
        - !GetAtt ImageMagick.Outputs.LayerVersion
    Type: AWS::Serverless::Function

  TransformMetadataFunction:
    Properties:
      CodeUri: ../lambda-functions/transform-metadata
      Description: "massages JSON of extracted image metadata"
      Handler: index.handler
      MemorySize: 256
      Timeout: 60
    Type: AWS::Serverless::Function

  StoreImageMetadataFunction:
    Properties:
      CodeUri:  ../lambda-functions/store-image-metadata
      Description: "Store image metadata into database"
      Handler: index.handler
      Policies:
        - Statement:
            - Sid: "AppSyncInvoke"
              Effect: Allow
              Action:
                - appsync:GraphQL
              Resource: !Sub "arn:aws:appsync:${AWS::Region}:${AWS::AccountId}:apis/${GraphQLAPIId}/*"
    Type: AWS::Serverless::Function

  RekognitionFunction:
    Properties:
      Description: "Use Amazon Rekognition to detect labels from image"
      Handler: index.handler
      MemorySize: 256
      Policies:
        - RekognitionDetectOnlyPolicy: {}
        - S3ReadPolicy:
            BucketName:
              !Ref PhotoRepoS3Bucket
      CodeUri:
        ../lambda-functions/rekognition
    Type: AWS::Serverless::Function

  GenerateThumbnailFunction:
    Properties:
      CodeUri:
        ../lambda-functions/thumbnail
      Description: "Generate thumbnails for images"
      Handler: index.handler
      MemorySize: 1536
      Timeout: 300
      Policies:
        - S3FullAccessPolicy:
            BucketName:
              !Ref PhotoRepoS3Bucket
      Layers:
        - !GetAtt ImageMagick.Outputs.LayerVersion
    Type: AWS::Serverless::Function

  # ---------------------------------------------------------------------------------------------------------------------
  # Step functions State Machine
  # ---------------------------------------------------------------------------------------------------------------------

  ImageProcStateMachine:
    Type: "AWS::Serverless::StateMachine"
    Properties:
      Name: !Sub PhotoProcessingWorkflow-${Stage}
      DefinitionUri: state-machine.asl.json
      DefinitionSubstitutions:
        ExtractImageMetadataFunction: !GetAtt ExtractImageMetadataFunction.Arn
        TransformMetadataFunction: !GetAtt TransformMetadataFunction.Arn
        GenerateThumbnailFunction: !GetAtt GenerateThumbnailFunction.Arn
        RekognitionFunction: !GetAtt RekognitionFunction.Arn
        StoreImageMetadataFunction: !GetAtt StoreImageMetadataFunction.Arn
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref GenerateThumbnailFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref RekognitionFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref ExtractImageMetadataFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref StoreImageMetadataFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref TransformMetadataFunction


Outputs:
  ProcessingStateMachine:
    Value:
      Ref: ImageProcStateMachine
